### ISSUE TITLE
Field coordinates versus relative

### ISSUE THREAD

**Issue by dbadb** [Spartronics4915/2020-InfiniteRecharge#117]
Need to be clear about how we'll deal with the field coordinates wrt odometry and starting alliance.  

As @j-james points out the field is symmetric.  If we go with the symmetric approach, then I guess we'd design all autonomous paths from the blue side, then flip the field in our heads and for display on the dashboard.

On the other hand if we simply always work in field coordinates, then we'll need to initialize odometry with alliance-specific values and flip the paths during match initialization.

The code in Vision.java subsystem, currently assumes that we're in absolute coords and will need to be changed for alliance-relative coords.

Any other dependencies on this question?

Please make a case for your preference and we'll then need to assign tasks to get there. 

Thanks!

**Comment by pietroglyph** [comment]
I think non-absolute coordinates may be the way to go. Flipping the field for display seems much easier than dealing with all the implications of absolute coordinations.

**Comment by dbadb** [comment]
Sounds good... Just to be clear:

* by non-absolute, I think we're talking about two different *absolute* coordinate systems selected according to alliance.  For blue we have x origin on left, but for red with have x-origin on right?
We'd also like to preserve the equivalence of the meaning of "right and left".  From blue, turning left means turning toward positive  y.  From red:  turning left means turning toward negative y
unless we flip the sense of y.  So I think that's really what we want, right?

```code looks best with fixed-width font
Blue                     Red
y+                    +x--- o
|                           |
o-- x+                      +y
```

* how do you plan to initialize odometry at the start of the match?  Are there multiple starting locations?  Will the driveteam select from a menu of starting locations?
