### ISSUE TITLE
IMU mishap mayhem

### ISSUE THREAD

**Issue by dbadb** [Spartronics4915/2020-InfiniteRecharge#128]
Need to figure out this issue pertaining to IMU resets.
My current suspicion is that it may have something to do with 180deg and the calculations of the offset.  

I think these things are true:

turn on robot and IMU calls it 0 degrees
run the drive straight test and it works
physically rotate the robot by 180, imu now says we're at 180 degrees.
run the drive straight test and it doesn't work.

My suggestion:  verify the underlying math behind the heading reset (simple as it is) and verify that the right values come out.  Ie: write a unit test.

**Comment by dbadb** [comment]
@pietroglyph @Elkwizard 

is it possible that two calls to setIMUHeading will accumulate?  ie:  when we call getIMUHeading in setIMUHeading, we're getting the combination of the previous mIMUOffset and the true IMU value.  Casual inspection suggests an alternate implementation of setIMUHeading:

``` java
 /* potential fix */
 public void setIMUHeading(Rotation2d heading)
 {
        mIMUOffset =  mIMU.getYaw().rotateBy(heading);
 }
 /* as checked-in */
public void setIMUHeading(Rotation2d heading)
 {
        mIMUOffset = getIMUHeading().rotateBy(heading.inverse());
 }
public Rotation2d getIMUHeading()
{
        return mIMU.getYaw().rotateBy(mIMUOffset);
}
```

**Comment by pietroglyph** [comment]
You and Henry fixed this, right?

**Comment by dbadb** [comment]
Yes!
