### ISSUE TITLE
Power cell trajectory calculations

### ISSUE THREAD

**Issue by omentic** [Spartronics4915/2020-InfiniteRecharge#3]
(this may be complete)

**Comment by pietroglyph** [comment]
Calculating the trajectory will probably not yield good results; there are too many difficult-to-model bits. We need to use an interpolating lookup table and find good values manually.

**Comment by omentic** [comment]
This is now a Week 5 milestone with current mechanical progress.

**Comment by omentic** [comment]
We're not going to implement this. The InterpolatingTreeMap + calcRPS/Pitch function better than a regression.
