### ISSUE TITLE
Add V-SLAM and PnP fusion

### ISSUE THREAD

**Issue by pietroglyph** [Spartronics4915/2020-InfiniteRecharge#34]

**Comment by pietroglyph** [comment]
Btw the PR for the EKF I'm writing can be found [here](https://github.com/mcm001/WPILibStateSpace/pull/5/files).

**Comment by dbadb** [comment]
ooh - neat!  Extended Kalman filtering!

next up:  Particle Filtering? https://en.wikipedia.org/wiki/Particle_filter

https://github.com/erhs-53-hackers/Particle-Filter/blob/master/src/particlefilter/ParticleFilter.java
