### ISSUE TITLE
Figure out color sensor output with the control panels

### ISSUE THREAD

**Issue by TheHarmonicRealm** [Spartronics4915/2020-InfiniteRecharge#38]
For the control panel, we need to test the color sensor's output and get maximum and minimum values for the RGB of the four colors; the values next to them are taken from [this image](https://andymark-weblinc.netdna-ssl.com/product_images/infinite-recharge-control-panel-sticker/5e1c8e6091b5fc38dab2fd1d/zoom.jpg?c=1578929760) and are extremely dubious:

- red (254,0,0)
- green (0,255,1)
- blue (0,255,255)
- yellow (255,255,0)

Also, the getRed, getGreen, and getBlue methods return 20-bit numbers; these should be converted to 8-bit to work in normal way.

**Comment by binnur** [comment]
@TheHarmonicRealm Take a look at the RevRobotics classes and sample code to get a feel about how the library would work. 

* [API docs](http://www.revrobotics.com/content/sw/color-sensor-v3/sdk/docs/javadoc/com/revrobotics/package-summary.html)
* [Sample code for testing color match](https://github.com/REVrobotics/Color-Sensor-v3-Examples/blob/master/Java/Color%20Match/src/main/java/frc/robot/Robot.java)

In the example, they are checking for `==` for color match. It will be important to play with confidence level and see if that would work better. TL;DR; look at how they are creating colors (this would be part of the calibration process) and using that for matching to results.

**Comment by binnur** [comment]
Adding comments from gmail. He observes that with the ranges used for color matching, `==` should work (along with the code as is) and no need to test for confidence levels.

--- From Riyadth:
> No need to roll our own. Just get this running. The only challenge I see is coming up with the constants for the colors we want to match. I think this means to collect data in as realistic a set of conditions as possible, and find a median sample to use for the constants. And it would be even better to be able to adjust these constants on individual fields (or even for each control panel on the field).

>But the first step is to get some actual code running on an actual RoboRIO. We were blocked from progress yesterday because the RoboRIO that Justice brought in did not seem to be imaged properly, and nobody knew how to proceed from that state.

**Comment by binnur** [comment]
More gmail comments

--- From Dana:
> On further inspection, the rev api accepts a list of target colors then produces a closest match.

>http://www.revrobotics.com/content/sw/color-sensor-v3/sdk/docs/javadoc/com/revrobotics/ColorMatch.html

>For the case where we know the entire set of expected colors, this is an excellent interface and will likely produce excellent results.
Simple as PI!

**Comment by TheHarmonicRealm** [comment]
Now this uses the built-in system, as soon as [this PR](https://github.com/Spartronics4915/2020-InfiniteRecharge/pull/89) is accepted. It now will look for the color that actually makes it line up; see [this diagram][1] for an explanation of sorts

Still need to test these colors.

[1]: https://drive.google.com/uc?id=1BfoFJmpJg31txUqTG-OrJjeWgQdQsCNC
