### ISSUE TITLE
core code cleanliness issues

### ISSUE THREAD

**Issue by dbadb** [Spartronics4915/2020-InfiniteRecharge#43]
Note: lib/math/twodim/trajectory/PathFinder.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

The serializable class CameraJNIException does not declare a static final serialVersionUID field of type long

**Comment by pietroglyph** [comment]
I dislike that VSCode warns about this because it’s only an issue in very specific situations where you’re serializing the exception and you want to maintain serialization compatibility across changes to the exception class. This is not what we’re doing, and we want the serialVersionUID to be generated automatically, which happens if you just don’t specify it.

**Comment by dbadb** [comment]
To be clear: I believe these warnings appear in command-line builds, so I don't think we can blame VSCode.  And in some production settings, it is a requirement to eliminate all warnings.  In the case where a warning is known to point to an acceptable case, there are often options that allow one to explicitly quell a warning... Not sure what the standard solution is for disabling individual warning in the java/gradle environment.

**Comment by pietroglyph** [comment]
These warnings don't appear in command line builds for me...

**Comment by dbadb** [comment]
Hmm - with up-to-date code, i currently see this:

Note:
C:\Users\dana\Documents\src\spartronics\2020-InfiniteRecharge\src\main\java\com\spartronics4915\lib\math\twodim\trajectory\PathFinder.java
uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Deprecated Gradle features were used in this build, making it incompatible
with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See
https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by pietroglyph** [comment]
I see that you suppressed the unchecked cast warning. As you probably found out by googling it, that unchecked cast doesn’t have an easy replacement.

**Comment by dbadb** [comment]
Yep

**Comment by dbadb** [comment]
closing
