### ISSUE TITLE
Finalize the list of LED animations for 2020 robot

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2020-InfiniteRecharge#47]
Review the [brainstorm list of LED animations](https://github.com/Spartronics4915/2020-InfiniteRecharge/wiki/Draft:-Robot-Bling#robot-states-and-bling-support) and finalize the list. Break the list into groups: **Must Haves** vs. **Wants** for prioritization. 

Note: it is useful to think of the animation sequence as a state diagram to capture the transitions in robot code for integration. I'll plan to add a draft example to the wiki.

**Comment by pietroglyph** [comment]
I think that vision target acquired is a must have.

**Comment by binnur** [comment]
Generally speaking, animations work best when they have time to display their pattern. In addition, we need to discuss the desired behavior and demonstrate we can meet that expectation. TL;DR -- while I like the idea of a visual animation for target acquired, if it is not done right it will be mixed into a sea of patterns that could be meaningless best case, distracting/confusing worse case -- ex. will the bling change to 'target acquired' as it is driving in the arena or when robot is in 'shooting' mode, and what do we want the driver to act on when the pattern animates? This is why we need to think through robot states, transitions, and desired driver actions.

Also note that the prioritization will help to limit the # of bling patterns -- we don't want to add cognitive overload of remembering what pattern was what to the driver.

**Comment by binnur** [comment]
Pls see the draft bling+robot states diagram on the wiki: https://github.com/Spartronics4915/2020-InfiniteRecharge/wiki/Draft:-Robot-Bling

**Comment by MayaShaw** [comment]
Here are list of commands:
```
  **NEEDS**
  BLING_COMMAND_STARTUP,
  BLING_COMMAND_DISABLED,
  BLING_COMMAND_DEFAULT,
  **WANTS**
  BLING_COMMAND_AUTOMODE,
  BLING_COMMAND_SHOOTING,
  BLING_COMMAND_PICKUP,
  BLING_COMMAND_LOADING,
  BLING_COMMAND_CLIMBING,
  BLING_COMMAND_VISION,
```
There is 9 so far, the majority in the wants. Depending on what would be useful I'm ideally looking to bring down the list to about 7 or below.

**Comment by riyadth** [comment]
Please make sure that there is a BLING_COMMAND_OFF to turn off all the LEDs. This will be important when we use the color sensor for the color wheel. Otherwise, the bling patterns will reflect off the control panel and there will be confusion.
I suggest that whenever the control panel manipulator is extended that the bling LEDs are turned off.

**Comment by randomgrace** [comment]
Right now, the 'OFF' is the 'BLING_COMMAND_SETUP' - this may be too
confusing.  Easy enough to change at this point.

-randy

**Comment by omentic** [comment]
Could there be a command for once the FMS has broadcast the target color?

**Comment by binnur** [comment]
If robot code handles extracting FMS color data, bling code can be added to send that pattern. During my Panel Rotator review, I recommended adding a `periodic()` code to check for FMS data. 

@j-james, reading your question, I am assuming your goal is to alert the driver about FMS stage readiness, correct? Couple of thoughts that requires consideration:
* If the goal is to send a specific FMS color (ex. red), this will require 4 different bling codes for each color -- there is no easy way to pass in a color parameter to Arduino code.
* The FMS bling code would be out-of-bound activity. Meaning, the FMS animation could be immediately overwritten by the next action driver takes, such as intaking. Similarly, if no other action takes place, animation could get stuck in the FMS animation mode. Note that, another alliance partner might have the control panel rotation responsibility.

Given this input, please connect w/ @MayaShaw to finalize this request.

**Comment by omentic** [comment]
After thinking about it, I'm going to retract my request - driver actions seem more important. Given that the control panel manipulator deals with the color wheel on its own, I don't see FMS colors being helpful.

**Comment by MayaShaw** [comment]
Draft animations are completed and will be adjusted if needed : )
