### ISSUE TITLE
Unit testing for the Control Panel Manipulator

### ISSUE THREAD

**Issue by omentic** [Spartronics4915/2020-InfiniteRecharge#83]
If we implement automatic functionality, this will need to test both.

**Comment by TheHarmonicRealm** [comment]
@j-james what is this saying we should do? I don't understand this issue.

**Comment by omentic** [comment]
@TheHarmonicRealm If you look at `/src/test/java/com/spartronics4915/frc2020`, you'll find some "Test" commands. Camden's is the only one currently working. 

The idea behind them is to run through your methods how they would be run on the real robot, and use `.logInfo` to log what it's currently doing.
