### ISSUE TITLE
migrate RobotContainer.throughTrench to separate DriveCommands.java

### ISSUE THREAD

**Issue by dbadb** [Spartronics4915/2020-InfiniteRecharge#86]
Before we start growing RobotContainer.java with lots of autonomous command implementations like throughTrench, is it worth migrating throughTrench to a separate file?  Then this line:

... whileHeld(new TrajectoryTrackerCommand(mDrive,
                throughTrench(), mRamseteController, mStateEstimator.getCameraRobotStateMap()))

could look something like:

... whileHeld(mTrajectoryCommands.new ThroughTrench(mDrive, mRamseteController, mStateEstimator)

and we'd hide/encapsulate the details of throughTrench into it's own private idaho.

thoughts?

**Comment by pietroglyph** [comment]
I would rather not use the trajectory tracker command by inheritance. I'll probably get @Elkwizard to move the `throughTrench` method to `TrajectoryContainer` or something.

**Comment by omentic** [comment]
d5a7e279b2e2344160f1b3b69682413d304cad04
