### ISSUE TITLE
Rewrite how ΔT is computed for each frame in vision

### ISSUE THREAD

**Issue by loqoman** [Spartronics4915/2020-InfiniteRecharge#94]
Because of the multi-threaded model in the vision codebase, the current code to determine the time it takes to run computations on any given frame is computed incorrectly.

The current proposed solution is to instead grab the current and final time from the networktables, as opposed to `time.monotonic()` in python. This _could_ solve the issue, however if the problem is more _where_ functions are called, switching to another source of time will not necessarily fix the problem

**Comment by dbadb** [comment]
If our goal is to measure a frame-time, i think we can do this in the thread-runner - perhaps we can look at this tonight.

Another thought:  write an offline algo-test: given a captured frame (or local image of the correct dimensions).   Run the algo on it X times and estimate the compute cost.   Now do this on pi3 and pi4 to get a sense of the relative performance.

**Comment by loqoman** [comment]
@dbadb Sorry I'm late on this,

After our discussion last night, computing the ΔT for each frame pi-side is unnecessary. Like you said, a robot `pose` has a timestamp associated with it, so simply returning our data with the time of the pose at the *start* of computation will work adequately.

After you left last night, @JeffreyTT and I finished capturing ~90 test frames at 1080p in the hallway. Jeffery put together a little script to go through each frame and eventually returns the average computation time for each frame. The 'parts' of the pipeline the script runs are everything after a frame is taken out of the oven (`algo.realPNP()`). As a preliminary number, the average computation time was around 10Hz. Initially, I'm a little skeptical of this number due to its vast difference from observed FPS when running `picamstreamer` (Which is < 1Hz). If these numbers are accurate, this experiment suggests that there is on the order of 1 second of delay that comes from *EITHER* the `picam` wrapper or code in `picamstreamer`. I'll get Jeffery to commit the script tonight so I can review it in depth.

**Comment by loqoman** [comment]
After some exploration, this seems to be either moot (due to grabbing timestamp from robot) or simply incorrect (proper Hz has been measured for camera capture and pipeline computation)
