### ISSUE TITLE
Rename bling command 'OFF' to match style

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2020-InfiniteRecharge#95]
Consistency in naming and styles are important for maintainability and understandability. Pls rename command `OFF` to match other bling commands. 

[See](https://github.com/MayaShaw/2020-InfiniteRecharge/blob/da2f95be7baf37f0b6c9aba0933afd8bec5a60b9/Arduino-Bling/RobotBling/RobotBling.ino#L82)

**Comment by randomgrace** [comment]
Maya,

Here's the two files I changed in the robot code (in 2020-InfiniteRecharge):

src/main/java/com/spartronics4915/frc2020/Robot.java
src/main/java/com/spartronics4915/frc2020/subsystems/LED.java

-randy

**Comment by binnur** [comment]
Done and changes merged.
