### ISSUE TITLE
Reorder the bling commands for consistency

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2020-InfiniteRecharge#96]
Needs should go with needs :) Please note that the bling commands need to reflect your committed list, not what was there previously. But, we do need `OFF` command :)

[See](https://github.com/MayaShaw/2020-InfiniteRecharge/blob/da2f95be7baf37f0b6c9aba0933afd8bec5a60b9/Arduino-Bling/RobotBling/RobotBling.ino#L94)

**Comment by MayaShaw** [comment]
Yeah pardon I have forgotten to add that, doing that right now. If you
don't mind me asking, could you explain the bling commands reflect
committed list sentence? I do not understand that well.

**Comment by binnur** [comment]
No worries — it is a formal product manager speak :) It basically means the list should reflect what you will be implementing in the code. With that, if you add functionality for ‘Wanted’ commands, you should move those to ‘Needs/Musts’ area for clarity.

**Comment by randomgrace** [comment]
Maya,

Here's the two files I changed in the robot code (in 2020-InfiniteRecharge):

src/main/java/com/spartronics4915/frc2020/Robot.java
src/main/java/com/spartronics4915/frc2020/subsystems/LED.java

-randy

**Comment by binnur** [comment]
@randomgrace ?? I don't see any changes to master code --> did you mean to push a PR?

**Comment by randomgrace** [comment]
Maya and I are working locally.  Neither of us have put in PRs.

-randy

**Comment by binnur** [comment]
updates merged
